title: Blog + Research Log
author: Quan Nguyen
email: manhquan233@gmail.com
description: >
  Blog + Research Log

remote_theme: aterenin/minima-reboot
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed
  - jekyll-redirect-from

minima_reboot:
  date_format: "%b %-d, %Y"
  date_format_short: "%b %-d"

header_pages:
- about.md
- posts.md
- researchlog.md
- github.md

footer_icons:
- username: Quan Nguyen
  url: https://github.com/ngmq
  icon: icon-github.svg

paginate: 5

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - minima-reboot.gemspec
